export interface WorldDefinition {
  id: number;
  name: string;
  subtitle: string;
  flavor: string;
  bg: string;
  starA: string;
  starB: string;
  accent: string;
  enemyPool: string[];
  bossType: string;
  bossName: string;
  musicTheme: string;
  difficulty: number;
  reward: string;
}

export const WORLD_DEFINITIONS: WorldDefinition[] = [
  {
    id: 1,
    name: 'Helios Verge',
    subtitle: 'Nebulosa de inicio',
    flavor: 'Explora una frontera azul con patrullas ligeras y una amenaza inicial controlable.',
    bg: '#020818',
    starA: '#aaddff',
    starB: '#ffffff',
    accent: '#00f7ff',
    enemyPool: ['drifter', 'weaver'],
    bossType: 'boss_mundo1',
    bossName: 'Aegis Dread',
    musicTheme: 'neon',
    difficulty: 1,
    reward: 'Recompensa: 150 monedas y mejora de escudo ligero',
  },
  {
    id: 2,
    name: 'Pyra Rift',
    subtitle: 'Ráfaga ardiente',
    flavor: 'Un corredor sobrecalentado con patrullas rápidas y una atmósfera abrasiva.',
    bg: '#12060b',
    starA: '#ffb86b',
    starB: '#ffe6a7',
    accent: '#ff5f6d',
    enemyPool: ['weaver', 'bomber', 'interceptor'],
    bossType: 'boss_dreadnought',
    bossName: 'Magma Warden',
    musicTheme: 'ember',
    difficulty: 1.25,
    reward: 'Recompensa: 220 monedas y carga extra de poder',
  },
  {
    id: 3,
    name: 'Ion Tomb',
    subtitle: 'Sector con tormenta eléctrica',
    flavor: 'Un espacio cargado de descargas y enemigos de alto impacto con movimiento errático.',
    bg: '#061522',
    starA: '#70f0ff',
    starB: '#d4fbff',
    accent: '#6ee7ff',
    enemyPool: ['tank', 'swarm', 'interceptor'],
    bossType: 'boss_sentinel',
    bossName: 'Ion Echo',
    musicTheme: 'ion',
    difficulty: 1.5,
    reward: 'Recompensa: 300 monedas y mejora de velocidad',
  },
  {
    id: 4,
    name: 'Abyss Circuit',
    subtitle: 'Cables y vacío profundo',
    flavor: 'Un sector con tensión artificial y enjambres que atacan desde las sombras.',
    bg: '#07070b',
    starA: '#c4b5fd',
    starB: '#f5f3ff',
    accent: '#8b5cf6',
    enemyPool: ['phantom', 'tank', 'weaver'],
    bossType: 'boss_nexus',
    bossName: 'Null Conductor',
    musicTheme: 'void',
    difficulty: 1.8,
    reward: 'Recompensa: 380 monedas y mejora de magneto',
  },
  {
    id: 5,
    name: 'Tempest Gate',
    subtitle: 'Puerta de huracanes',
    flavor: 'Más presión atmosférica, más criaturas de ataque y menos margen para errores.',
    bg: '#08111b',
    starA: '#7dd3fc',
    starB: '#d7f3ff',
    accent: '#38bdf8',
    enemyPool: ['bomber', 'phantom', 'swarm'],
    bossType: 'boss_sentinel',
    bossName: 'Storm Titan',
    musicTheme: 'storm',
    difficulty: 2.15,
    reward: 'Recompensa: 450 monedas y mejora de suerte',
  },
  {
    id: 6,
    name: 'Obsidian Crown',
    subtitle: 'Corona de presión negra',
    flavor: 'El horror más pesado del sector: masas de fuego y mandos de alta resistencia.',
    bg: '#090909',
    starA: '#f59e0b',
    starB: '#fcd34d',
    accent: '#f97316',
    enemyPool: ['tank', 'bomber', 'phantom'],
    bossType: 'boss_dreadnought',
    bossName: 'Obsidian King',
    musicTheme: 'obsidian',
    difficulty: 2.5,
    reward: 'Recompensa: 520 monedas y escudo reforzado',
  },
  {
    id: 7,
    name: 'Aurora Prime',
    subtitle: 'Luz polar sobre el vacío',
    flavor: 'Una aurora hostil con enemigos de alta agilidad y giros de persecución.',
    bg: '#03161c',
    starA: '#a7f3d0',
    starB: '#ecfeff',
    accent: '#34d399',
    enemyPool: ['weaver', 'swarm', 'interceptor', 'phantom'],
    bossType: 'boss_nexus',
    bossName: 'Aurora Wraith',
    musicTheme: 'aurora',
    difficulty: 2.9,
    reward: 'Recompensa: 640 monedas y aumento de daño crítico',
  },
  {
    id: 8,
    name: 'Black Halo',
    subtitle: 'Anillo oscuro de colapso',
    flavor: 'Una órbita de destruccón donde los enemigos mantienen una presión constante.',
    bg: '#050507',
    starA: '#e879f9',
    starB: '#fdf4ff',
    accent: '#d946ef',
    enemyPool: ['bomber', 'tank', 'interceptor', 'phantom'],
    bossType: 'boss_sentinel',
    bossName: 'Halo Reaver',
    musicTheme: 'shadow',
    difficulty: 3.2,
    reward: 'Recompensa: 760 monedas y mejora de disparo múltiple',
  },
  {
    id: 9,
    name: 'Eclipse Core',
    subtitle: 'Núcleo totalmente eclipsado',
    flavor: 'El mayor nivel de caos con enemigos pesados y ritmos de fuego muy agresivos.',
    bg: '#0a0a14',
    starA: '#fda4af',
    starB: '#fff1f2',
    accent: '#fb7185',
    enemyPool: ['tank', 'bomber', 'swarm', 'interceptor'],
    bossType: 'boss_nexus',
    bossName: 'Eclipse Sovereign',
    musicTheme: 'eclipse',
    difficulty: 3.7,
    reward: 'Recompensa: 880 monedas y núcleo de energía de alto valor',
  },
  {
    id: 10,
    name: 'Astral Dominion',
    subtitle: 'Último bastión del cosmos',
    flavor: 'La última frontera: una mezcla de velocidad, resistencia y presión total del dominio astral.',
    bg: '#090b20',
    starA: '#c084fc',
    starB: '#f5f3ff',
    accent: '#a855f7',
    enemyPool: ['phantom', 'bomber', 'tank', 'interceptor', 'swarm'],
    bossType: 'boss_dreadnought',
    bossName: 'Dominion Core',
    musicTheme: 'astral',
    difficulty: 4.25,
    reward: 'Recompensa: 1200 monedas y acceso al modo Nuevo Juego+',
  },
];

export const getWorldDefinition = (world: number) => {
  const match = WORLD_DEFINITIONS.find(w => w.id === world);
  if (match) return match;
  return WORLD_DEFINITIONS[0];
};
